/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clickergame;
import javax.swing.*;
import java.awt.BorderLayout;
import java.util.TimerTask;
/**
 *
 * @author user
 */
public class mainscreen extends javax.swing.JPanel {
JFrame newFrame = new JFrame();
private int numClicks = 0;
private int modClicks1 = 1, modClicks2 = 1;
private boolean jbutton3_condition = true;

java.util.Timer t1 = new java.util.Timer();
    /**
     * Creates new form mainscreen
     */
    public mainscreen() {
        initComponents();
        newFrame.getContentPane().add(this, BorderLayout.CENTER);
        newFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        newFrame.pack();
        newFrame.setVisible(true);
        newFrame.setTitle("Clicker Game");
        initialConditions();
    }

    public void initialConditions(){
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jLabel1.setText(numClicks + "");
    }
    
    public void checkButtonsCondition(){
        if(numClicks >= 10){jButton2.setEnabled(true);}
        else {jButton2.setEnabled(false);}
        if(numClicks >= 100){jButton3.setEnabled(true);}
        else {jButton3.setEnabled(false);}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("Clicks (+1)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        jButton2.setText("More Clicks (-10)");
        jButton2.setToolTipText("Add more clicks for the main button");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Auto-Clicker (-100)");
        jButton3.setToolTipText("Get 1 click per 5 seconds");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 178, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        numClicks = numClicks + modClicks1;
        jLabel1.setText(numClicks + "");
        jButton1.setText("Clicks (+" + modClicks1 + ")");
        checkButtonsCondition();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(numClicks >= 10){
            numClicks = numClicks - 10;
            modClicks1++;
            jLabel1.setText(numClicks + "");
            jButton1.setText("Clicks (+" + modClicks1 + ")");
            checkButtonsCondition();
        }
        else {
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jbutton3_condition == true){
            t1.schedule(new TimerTask(){
                @Override
                public void run(){
                    numClicks = numClicks + modClicks2;
                    jLabel1.setText(numClicks + "");
                }
            }, 5000, 5000);
            jbutton3_condition = false;
        }
        else {
            modClicks2++;
        }
        numClicks = numClicks - 100;
        jLabel1.setText(numClicks + "");
        jButton3.setToolTipText(modClicks2 + " clicks per 5 seconds");
        checkButtonsCondition();
        //jButton3.setEnabled(false);    //Disable the button
        //jButton3.setVisible(false);    //'remove' the button
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
